// Package replay holds Go types for Datadog Session Replay segments, the
// JSON found inside the zlib-compressed `segment` part of a /api/v2/replay
// multipart request, as published by DataDog/rum-events-format
// (session-replay/segment-schema.json: a browser segment with rrweb-style
// records, or a mobile segment with wireframe records).
//
// It is a sibling of package rumevents rather than part of it because replay
// is a different intake track with a different body format and its own
// discriminator space (integer record types, integer incremental sources);
// keeping it apart leaves the RUM event API untouched. Both packages are
// generated by the same generator from the same schema checkout and share
// the same guarantees:
//
//   - Nothing is lost. Every object keeps undeclared keys in
//     AdditionalProperties and writes them back on encode, even where the
//     schema says additionalProperties: false. A record, node or wireframe
//     whose discriminator matches no known variant is kept verbatim in the
//     union envelope's Raw field instead of failing the whole segment.
//   - No number goes through float64: `integer` is int64, `number` is
//     json.Number, unknown values are decoded with UseNumber. Heterogeneous
//     tuples (change records) are []any with json.Number elements.
//   - Variants are selected by the discriminators the schema declares
//     (`source` for segments, `type` for records and DOM nodes, `source` for
//     incremental data, `type` for wireframes and layer modifiers), never by
//     shape.
//
// Nested unions are envelopes: a struct with one pointer per variant plus
// Raw; Variant() returns whichever is set. The recursive DOM tree closes
// through them: DocumentNodeWithId.ChildNodes is []SerializedNodeWithId.
//
// Decode takes one decompressed segment and returns the concrete segment
// type behind the Segment interface:
//
//	seg, err := replay.Decode(segmentJSON)
//	switch s := seg.(type) {
//	case *replay.BrowserSegment:
//		for _, r := range s.Records { if r.BrowserFullSnapshotV1Record != nil { ... } }
//	case *replay.MobileSegment:
//	}
//
// Regeneration (requires a checkout of DataDog/rum-events-format):
//
//	RUM_EVENTS_FORMAT=/path/to/rum-events-format go generate ./rumevents/...
package replay

//go:generate go run ../internal/gen -preset replay -schemas $RUM_EVENTS_FORMAT/schemas -out .
